[CREDENTIALS]
URL = https://signin.definedgesecurities.com/auth/realms/debroking/protocol/openid-connect/auth?response_type=code&client_id=dashboard&redirect_uri=https://myaccount.definedgesecurities.com/ssologin&state=e2cf559f-356c-425a-87e3-032097f643d0&login=true&scope=openid
UCC      = 1266757
PASSWORD = @!@!102Sa
TOTP_SECRET = MVGEWMTZJAYUY2CIO5WTISSJNNTGK5LS

[SETTINGS]
; Folder where downloaded files will be saved
DOWNLOAD_DIR = C:\Trading\rotational_investing_system\Monthly Stock Portfolios Rankings_AUTOMATED

[STRATEGIES]
; Add one strategy name per line (exactly as it appears in the dropdown)
LIST =
	MIP 37 As is
	MIP-34
	MIP Mid150 Monthly
	MIP Sml250 Monthly
	MIP Mid150 Weekly
	MIP Sml250 Weekly
    ETF_MONTHLY_1
    ETF_MONTHLY_2
	ETF_WEEKLY

[TELEGRAM]
; Get BOT_TOKEN from @BotFather on Telegram
; Get CHAT_ID from @userinfobot or @getidsbot (use group chat ID for groups, e.g. -1001234567890)
; Leave blank to disable Telegram notifications
BOT_TOKEN = 1384724960:AAExUMqkFFjqfixP_pDD8Nkr2sNgk34ohsk
CHAT_ID = -1002642134152
