"""
DefineE RZ Momentum Scanner — CI / GitHub Actions Version
==========================================================
Headless Chromium, reads config.ini (built by build_config.py from env vars),
saves screenshots on failure for debugging, uploads artifacts.

Usage (CI):
    python ci/build_config.py        # generates config.ini from env vars
    python ci/rz_scanner_ci.py       # runs headless scan
"""

import asyncio
import configparser
import pyotp
import re
import sys
import time
import requests
from pathlib import Path
from datetime import datetime
from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeout


# ─────────────────────────────────────────────────────────────────────────────
# Load config.ini (generated by build_config.py)
# ─────────────────────────────────────────────────────────────────────────────
CONFIG_PATH = Path(__file__).parent.parent / "config.ini"

def load_config():
    config = configparser.ConfigParser()
    if not CONFIG_PATH.exists():
        print(f"ERROR: config.ini not found at {CONFIG_PATH}")
        print("Run `python ci/build_config.py` first to generate it from env vars.")
        sys.exit(1)
    config.read(CONFIG_PATH)
    return config

config       = load_config()
UCC          = config["CREDENTIALS"]["UCC"].strip()
PASSWORD     = config["CREDENTIALS"]["PASSWORD"].strip()
TOTP_SECRET  = config["CREDENTIALS"]["TOTP_SECRET"].strip()
DOWNLOAD_DIR = Path(config["SETTINGS"]["DOWNLOAD_DIR"].strip())
STRATEGIES   = [s.strip() for s in config["STRATEGIES"]["LIST"].strip().splitlines() if s.strip()]

TG_TOKEN   = config.get("TELEGRAM", "BOT_TOKEN", fallback="").strip()
TG_CHAT_ID = config.get("TELEGRAM", "CHAT_ID", fallback="").strip()
TG_ENABLED = bool(TG_TOKEN and TG_CHAT_ID)

DATE_STR = datetime.now().strftime("%d_%m_%Y")

# Morning (7:15 AM IST ≈ 1:45 UTC) or Evening (9:00 PM IST ≈ 15:30 UTC)
import os
RUN_LABEL = os.environ.get("RZ_RUN_LABEL", "").strip()
if not RUN_LABEL:
    from datetime import timezone
    utc_hour = datetime.now(timezone.utc).hour
    RUN_LABEL = "morning" if utc_hour < 12 else "evening"

DOWNLOAD_DIR = DOWNLOAD_DIR / DATE_STR
DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)

# Screenshots directory for debugging
SCREENSHOTS_DIR = Path(__file__).parent.parent / "screenshots"
SCREENSHOTS_DIR.mkdir(parents=True, exist_ok=True)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────
def log(msg):
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)

def separator(title=""):
    print(f"\n{'─' * 55}", flush=True)
    if title:
        print(f"  {title}", flush=True)
        print(f"{'─' * 55}", flush=True)

def tg(msg):
    if not TG_ENABLED:
        return
    try:
        url = f"https://api.telegram.org/bot{TG_TOKEN}/sendMessage"
        requests.post(url, data={"chat_id": TG_CHAT_ID, "text": msg, "parse_mode": "HTML"}, timeout=10)
    except Exception:
        pass

def tg_file(file_path, caption=""):
    if not TG_ENABLED:
        return
    try:
        url = f"https://api.telegram.org/bot{TG_TOKEN}/sendDocument"
        with open(file_path, "rb") as f:
            requests.post(
                url,
                data={"chat_id": TG_CHAT_ID, "caption": caption, "parse_mode": "HTML"},
                files={"document": (Path(file_path).name, f)},
                timeout=30
            )
        log(f"Sent to Telegram: {Path(file_path).name}")
    except Exception as e:
        log(f"Telegram file send failed: {e}")

def notify(msg):
    log(msg)
    tg(msg)

async def dismiss_overlay(page):
    """Dismiss any GWT popup glass overlay that blocks pointer events."""
    try:
        glass = page.locator("div.gwt-PopupPanelGlass")
        if await glass.first.is_visible():
            log("GWT overlay detected — dismissing...")
            await page.keyboard.press("Escape")
            await asyncio.sleep(0.5)
            if await glass.first.is_visible():
                await page.evaluate(
                    "document.querySelectorAll('.gwt-PopupPanelGlass').forEach(e => e.remove())"
                )
                await asyncio.sleep(0.3)
                log("Overlay removed via JS")
            else:
                log("Overlay dismissed via Escape")
    except Exception:
        pass

async def save_screenshot(page, name):
    """Save a debug screenshot (for CI artifact upload)."""
    try:
        ts = datetime.now().strftime("%H%M%S")
        path = SCREENSHOTS_DIR / f"{ts}_{name}.png"
        await page.screenshot(path=path, full_page=True)
        log(f"Screenshot saved: {path.name}")
    except Exception as e:
        log(f"Screenshot failed: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────
async def run():
    separator("DefineE RZ Scanner — CI / Headless Mode")
    log(f"Strategies : {STRATEGIES}")
    log(f"Save folder: {DOWNLOAD_DIR}")
    log(f"Date suffix: {DATE_STR}")
    log(f"Run label  : {RUN_LABEL}")
    log(f"Telegram   : {'Enabled' if TG_ENABLED else 'Disabled'}")
    log(f"Screenshots: {SCREENSHOTS_DIR}")

    if not STRATEGIES:
        log("ERROR: No strategies configured.")
        sys.exit(1)

    tg(f"🚀 <b>RZ Scanner Started (CI — {RUN_LABEL})</b>\n"
       f"Strategies: {len(STRATEGIES)}\n"
       f"Date: {DATE_STR}")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=True,
            args=[
                "--no-sandbox",
                "--disable-setuid-sandbox",
                "--disable-dev-shm-usage",
                "--disable-gpu",
                "--window-size=1920,1080",
            ]
        )
        # Use a real-looking user agent to avoid headless detection
        context = await browser.new_context(
            viewport={"width": 1920, "height": 1080},
            accept_downloads=True,
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/122.0.0.0 Safari/537.36"
            ),
        )
        page = await context.new_page()


        # ── STEP 1: Go directly to login URL (skip home page in CI) ────────
        separator("STEP 1: Opening Login Page")
        login_url = config["CREDENTIALS"].get("URL", "").strip()
        if not login_url:
            log("ERROR: Login URL not set. Add it to config.ini [CREDENTIALS] URL, or set RZ_LOGIN_URL secret.")
            sys.exit(1)
        log("Navigating to login URL...")
        page1 = page  # In CI, go directly — no home page popup dance
        await page1.goto(login_url, wait_until="domcontentloaded", timeout=60000)
        log("Login page loaded.")
        await save_screenshot(page1, "login_page_loaded")

        # Wait for UCC field to confirm login form is ready
        await page1.get_by_role("textbox", name="UCC").wait_for(state="visible", timeout=30000)
        log("Login form ready.")


        # ── STEP 3: Enter UCC + Password ─────────────────────────────────────
        separator("STEP 3: Credentials")
        log("Filling UCC...")
        await page1.get_by_role("textbox", name="UCC").click()
        await page1.get_by_role("textbox", name="UCC").fill(UCC)
        log(f"UCC entered: {UCC}")

        log("Filling Password...")
        await page1.get_by_role("textbox", name=re.compile(r"Password", re.IGNORECASE)).click()
        await page1.get_by_role("textbox", name=re.compile(r"Password", re.IGNORECASE)).fill(PASSWORD)
        log("Password entered.")

        log("Clicking Sign In...")
        await page1.get_by_role("button", name="Sign In").click()


        # ── STEP 4: OTP (auto-generated) ─────────────────────────────────────
        separator("STEP 4: OTP (Auto)")
        log("Waiting for OTP page...")
        await page1.get_by_role("textbox", name=re.compile(r"Code", re.IGNORECASE)).wait_for(
            state="visible", timeout=30000
        )
        log("OTP field ready.")

        totp   = pyotp.TOTP(TOTP_SECRET)
        code   = totp.now()
        expiry = 30 - (datetime.now().second % 30)
        log(f"Generated OTP: {code}  (valid for ~{expiry}s)")
        await page1.get_by_role("textbox", name=re.compile(r"Code", re.IGNORECASE)).click()
        await page1.get_by_role("textbox", name=re.compile(r"Code", re.IGNORECASE)).fill(code)
        log("OTP entered.")

        await page1.get_by_role("button", name="Submit").click()
        log("Submit clicked.")


        # ── STEP 5: Wait for MyAccount ────────────────────────────────────────
        separator("STEP 5: MyAccount")
        log("Waiting for MyAccount / Analyse & Trade to appear...")
        analyse_btn = page1.get_by_role("button", name="Analyse & Trade")
        for _ in range(120):
            try:
                if await analyse_btn.is_visible():
                    log(f"MyAccount loaded →  {page1.url}")
                    break
            except Exception:
                pass
            await asyncio.sleep(0.5)
        else:
            await save_screenshot(page1, "myaccount_timeout")
            log("Analyse & Trade not found in 60s — attempting anyway...")

        notify("✅ Logged in to MyAccount")


        # ── STEP 6: Analyse & Trade → Opens RZone popup ──────────────────────
        separator("STEP 6: RZ → Analyse & Trade")
        log("Clicking Analyse & Trade button...")
        async with page1.expect_popup() as page2_info:
            await analyse_btn.click()
        page2 = await page2_info.value
        log(f"RZ popup captured →  {page2.url}")

        # RZ SPA does client-side redirects — wait for page to stabilize
        log("Waiting for RZone page to settle...")
        for _ in range(30):
            try:
                await page2.wait_for_load_state("domcontentloaded", timeout=5000)
                await asyncio.sleep(1)
                body_len = await page2.evaluate("document.body ? document.body.innerText.length : 0")
                if body_len > 100:
                    break
            except Exception as e:
                log(f"Page still loading/navigating... ({type(e).__name__})")
                await asyncio.sleep(1)

        await asyncio.sleep(1)
        log(f"RZ page ready →  {page2.url}")
        await save_screenshot(page2, "rz_loaded")


        # ── STEP 7: I Agree (may or may not appear) ─────────────────────────
        separator("STEP 7: I Agree")
        log("Waiting for I Agree or page to be ready...")

        i_agree_by_role  = page2.get_by_role("button", name="I Agree")
        i_agree_by_text  = page2.get_by_text(re.compile(r"^I\s*Agree$", re.IGNORECASE))
        i_agree_by_xpath = page2.locator("xpath=//button[contains(text(),'Agree')] | //a[contains(text(),'Agree')] | //div[contains(text(),'Agree')] | //span[contains(text(),'Agree')]")
        page_ready       = page2.get_by_text("Momentum Scanner")

        found = False
        for tick in range(90):
            try:
                if await i_agree_by_role.is_visible():
                    await i_agree_by_role.click()
                    log("Clicked I Agree (button role)")
                    await asyncio.sleep(2)
                    found = True
                    break
            except Exception:
                pass
            try:
                if await i_agree_by_text.first.is_visible():
                    await i_agree_by_text.first.click()
                    log("Clicked I Agree (text match)")
                    await asyncio.sleep(2)
                    found = True
                    break
            except Exception:
                pass
            try:
                if await i_agree_by_xpath.first.is_visible():
                    await i_agree_by_xpath.first.click()
                    log("Clicked I Agree (xpath match)")
                    await asyncio.sleep(2)
                    found = True
                    break
            except Exception:
                pass
            try:
                if await page_ready.is_visible():
                    log("I Agree not shown — already accepted. Continuing...")
                    found = True
                    break
            except Exception:
                pass
            if tick == 20:
                for frame in page2.frames:
                    try:
                        frame_agree = frame.get_by_text(re.compile(r"I\s*Agree", re.IGNORECASE))
                        if await frame_agree.first.is_visible():
                            await frame_agree.first.click()
                            log("Clicked I Agree (inside iframe)")
                            await asyncio.sleep(2)
                            found = True
                            break
                    except Exception:
                        pass
                if found:
                    break
            await asyncio.sleep(0.5)

        if not found:
            await save_screenshot(page2, "i_agree_not_found")
            log("Neither I Agree nor page content found in 45s — continuing anyway...")


        # ── STEP 8: Momentum Scanner ─────────────────────────────────────────
        separator("STEP 8: Opening Momentum Scanner")
        log("Clicking Momentum Scanner...")
        await page2.get_by_text("Momentum Scanner").click()
        await asyncio.sleep(1)

        log("Clicking Momentum Investing Scanner...")
        await page2.get_by_role("link", name=re.compile(r"Momentum Investing Scanner", re.IGNORECASE)).click()
        await asyncio.sleep(3)

        log("Waiting for scanner panel to load...")
        await page2.get_by_role("button", name="Scan").wait_for(state="visible", timeout=30000)
        log("Momentum Investing Scanner opened")

        notify("✅ RZ Momentum Scanner ready")
        await save_screenshot(page2, "scanner_ready")


        # ── STEP 9: Loop through strategies ─────────────────────────────────
        results = []

        for idx, strategy in enumerate(STRATEGIES, 1):
            separator(f"Strategy {idx}/{len(STRATEGIES)}: {strategy}")
            notify(f"📊 Scanning {idx}/{len(STRATEGIES)}: <b>{strategy}</b>")

            MAX_ATTEMPTS = 2
            for attempt in range(1, MAX_ATTEMPTS + 1):
                try:
                    if attempt > 1:
                        log(f"RETRY attempt {attempt}/{MAX_ATTEMPTS} for {strategy}")
                        notify(f"🔄 Retrying <b>{strategy}</b> (attempt {attempt})")
                        await asyncio.sleep(3)

                    # Dismiss any leftover GWT overlay from previous strategy
                    await dismiss_overlay(page2)

                    # 9a. Check Mmfy checkbox
                    log("Checking Mmfy checkbox...")
                    mmfy_label = page2.get_by_role("cell", name=re.compile(r"Group\s*:")).locator("label")
                    await mmfy_label.wait_for(state="visible", timeout=15000)
                    await mmfy_label.click()
                    await asyncio.sleep(0.3)
                    log("Mmfy: checked")

                    # 9b. Select strategy from dropdown
                    log(f"Selecting strategy: '{strategy}'")
                    dropdown = None
                    try:
                        dropdown = page2.locator("select").filter(
                            has=page2.locator("option", has_text=re.compile(r"Momentify", re.IGNORECASE))
                        ).first
                        await dropdown.wait_for(state="visible", timeout=2000)
                    except PlaywrightTimeout:
                        dropdown = None

                    if dropdown is None:
                        try:
                            dropdown = page2.get_by_role("cell", name=re.compile(r"Select Momentify|Momentify", re.IGNORECASE)).get_by_role("combobox")
                            await dropdown.wait_for(state="visible", timeout=2000)
                        except PlaywrightTimeout:
                            dropdown = None

                    if dropdown is None:
                        dropdown = page2.locator("select:visible").first
                        await dropdown.wait_for(state="visible", timeout=5000)

                    await dropdown.select_option(strategy)
                    await asyncio.sleep(0.8)
                    log(f"Strategy '{strategy}' selected")

                    # 9c. Uncheck Mmfy checkbox
                    await dismiss_overlay(page2)
                    log("Unchecking Mmfy checkbox...")
                    mmfy_label_after = page2.get_by_role("cell", name=re.compile(r"Group\s*:")).locator("label")
                    await mmfy_label_after.wait_for(state="visible", timeout=10000)
                    await mmfy_label_after.click()
                    await asyncio.sleep(0.8)
                    log("Mmfy: unchecked")

                    # 9c2. Market trend Filter — only if enabled
                    market_filter_btn = page2.get_by_text(re.compile(r"Market.*trend.*Filter|Market.*Filter", re.IGNORECASE)).first
                    market_filter_enabled = False
                    try:
                        await market_filter_btn.wait_for(state="visible", timeout=3000)
                        is_disabled = await market_filter_btn.is_disabled()
                        opacity = await market_filter_btn.evaluate("el => getComputedStyle(el).opacity")
                        pointer = await market_filter_btn.evaluate("el => getComputedStyle(el).pointerEvents")
                        if is_disabled or float(opacity) < 0.5 or pointer == "none":
                            log("Market trend Filter is DISABLED — skipping to Scan.")
                        else:
                            market_filter_enabled = True
                    except PlaywrightTimeout:
                        log("Market trend Filter not found — skipping to Scan.")

                    if market_filter_enabled:
                        log("Market trend Filter is ENABLED — clicking...")
                        try:
                            await market_filter_btn.click()
                            await asyncio.sleep(1)
                            log("Market trend Filter popup opened.")
                            save_btn = page2.locator("xpath=/html/body/div[7]/div/table/tbody/tr[3]/td/div/table/tbody/tr/td[1]/button")
                            try:
                                await save_btn.wait_for(state="visible", timeout=5000)
                                await save_btn.click()
                            except PlaywrightTimeout:
                                await page2.get_by_role("button", name=re.compile(r"Save", re.IGNORECASE)).first.click()
                            await asyncio.sleep(0.5)
                            log("Market trend Filter: SAVE clicked")
                        except PlaywrightTimeout:
                            log("Market trend Filter popup/SAVE not found — continuing...")

                    # 9d. Click Scan
                    filter_not_qualified = False
                    no_qualified_scrips  = False
                    log("Clicking Scan button...")
                    await page2.get_by_role("button", name="Scan").click()
                    log("Scan started...")

                    # 9e. Wait for scan result
                    CANCEL_RETRY_SECS = 8 * 60
                    HARD_TIMEOUT_SECS = 15 * 60
                    STUCK_THRESHOLD   = 90

                    log(f"Waiting for scan (max {HARD_TIMEOUT_SECS//60}min, "
                        f"cancel at {CANCEL_RETRY_SECS//60}min, stuck at {STUCK_THRESHOLD}s)...")
                    export_btn = page2.get_by_role("button", name="Export")
                    scan_completed_text = page2.get_by_text(re.compile(r"Scan\s*Completed", re.IGNORECASE))
                    validation_popup = page2.get_by_text(re.compile(r"Validation Filter.*not qualified|Filter.*not qualified", re.IGNORECASE))
                    processing_text  = page2.get_by_text(re.compile(r"Processing", re.IGNORECASE))
                    cancel_btn       = page2.get_by_role("button", name=re.compile(r"Cancel", re.IGNORECASE))

                    scan_done = False
                    scan_start = time.time()
                    already_cancelled = False
                    last_progress_str  = ""
                    last_progress_time = time.time()

                    while True:
                        elapsed = time.time() - scan_start

                        if elapsed > HARD_TIMEOUT_SECS:
                            await save_screenshot(page2, f"timeout_{strategy}")
                            log(f"Timed out waiting for scan ({HARD_TIMEOUT_SECS//60} mins).")
                            notify(f"⚠️ <b>{strategy}</b>: Scan timed out after {HARD_TIMEOUT_SECS//60} mins")
                            break

                        # Stuck detection
                        current_progress_str = ""
                        try:
                            if await processing_text.first.is_visible():
                                current_progress_str = (await processing_text.first.text_content() or "").strip()
                        except Exception:
                            pass

                        if current_progress_str:
                            if current_progress_str != last_progress_str:
                                last_progress_str  = current_progress_str
                                last_progress_time = time.time()
                            else:
                                stuck_secs = time.time() - last_progress_time
                                if stuck_secs >= STUCK_THRESHOLD and not already_cancelled:
                                    log(f"Processing STUCK for {int(stuck_secs)}s at: {current_progress_str}")
                                    await save_screenshot(page2, f"stuck_{strategy}")
                                    notify(f"🔒 <b>{strategy}</b>: Stuck at '{current_progress_str}' — cancelling")
                                    try:
                                        await cancel_btn.first.click()
                                        await asyncio.sleep(2)
                                        await page2.get_by_role("button", name="Scan").click()
                                        log("Re-scan started after stuck cancel.")
                                        scan_start = time.time()
                                        last_progress_str  = ""
                                        last_progress_time = time.time()
                                        already_cancelled = True
                                    except Exception as e:
                                        log(f"Stuck cancel/rescan failed: {e}")
                                    continue

                        # Time-based cancel
                        if elapsed > CANCEL_RETRY_SECS and not already_cancelled:
                            is_processing = False
                            try:
                                is_processing = await processing_text.first.is_visible()
                            except Exception:
                                pass
                            if is_processing:
                                log(f"Still processing after {CANCEL_RETRY_SECS//60}min — cancelling & retrying...")
                                await save_screenshot(page2, f"slow_{strategy}")
                                notify(f"⏳ <b>{strategy}</b>: Cancelling slow scan, retrying...")
                                try:
                                    await cancel_btn.first.click()
                                    await asyncio.sleep(2)
                                    await page2.get_by_role("button", name="Scan").click()
                                    log("Re-scan started after time-based cancel.")
                                    scan_start = time.time()
                                    last_progress_str  = ""
                                    last_progress_time = time.time()
                                    already_cancelled = True
                                except Exception as e:
                                    log(f"Cancel/rescan failed: {e}")
                                continue

                        # Validation filter popup
                        try:
                            if await validation_popup.first.is_visible():
                                log("Validation Filter not qualified!")
                                filter_not_qualified = True
                                log("Closing popup...")
                                close_btn = page2.locator("xpath=/html/body/div[7]/div/table/tbody/tr[3]/td/div/table/tbody/tr/td/button")
                                try:
                                    await close_btn.wait_for(state="visible", timeout=3000)
                                    await close_btn.click()
                                except PlaywrightTimeout:
                                    await page2.get_by_role("button", name=re.compile(r"Close|OK", re.IGNORECASE)).first.click()
                                await asyncio.sleep(1)
                                log("Popup closed.")

                                log("Unchecking Market trend filter...")
                                market_filter_cb = page2.locator(
                                    "xpath=/html/body/div[4]/div[2]/div/div[2]/div[3]/div/div[3]"
                                    "/div/div/div[2]/div/table[1]/tbody/tr[1]/td[5]/table/tbody/tr/td[1]"
                                )
                                try:
                                    await market_filter_cb.wait_for(state="visible", timeout=3000)
                                    await market_filter_cb.click()
                                except PlaywrightTimeout:
                                    mf = page2.get_by_role("cell", name=re.compile(r"Market.*Filter|Market.*Trend", re.IGNORECASE)).locator("label, input, span").first
                                    await mf.click()
                                await asyncio.sleep(0.5)
                                log("Market trend filter unchecked")
                                notify(f"⚠️ <b>{strategy}</b>: Filter not qualified — re-scanning")

                                log("Re-scanning without market filter...")
                                await page2.get_by_role("button", name="Scan").click()
                                log("Re-scan started...")
                                scan_start = time.time()
                                last_progress_str  = ""
                                last_progress_time = time.time()
                                continue
                        except Exception:
                            pass

                        # Check 0 qualified scrips
                        try:
                            zero_scrips = page2.get_by_text(re.compile(r"Qualified Scrips\s*:\s*0", re.IGNORECASE))
                            if await zero_scrips.first.is_visible():
                                elapsed_s = int(time.time() - scan_start)
                                log(f"Scan completed — 0 qualified scrips ({elapsed_s}s)")
                                no_qualified_scrips = True
                                scan_done = True
                                break
                        except Exception:
                            pass

                        # Check Export enabled
                        try:
                            if await export_btn.is_visible() and await export_btn.is_enabled():
                                elapsed_s = int(time.time() - scan_start)
                                log(f"Scan completed! ({elapsed_s}s)")
                                scan_done = True
                                break
                        except Exception:
                            pass

                        # Check "Scan Completed" text
                        try:
                            if await scan_completed_text.first.is_visible():
                                elapsed_s = int(time.time() - scan_start)
                                log(f"'Scan Completed' text detected ({elapsed_s}s)")
                                await asyncio.sleep(1)
                                scan_done = True
                                break
                        except Exception:
                            pass

                        # Log progress every 15s
                        if int(elapsed) % 15 == 0 and int(elapsed) > 0:
                            if current_progress_str:
                                log(f"  {current_progress_str}  ({int(elapsed)}s)")
                            else:
                                try:
                                    is_proc = await processing_text.first.is_visible()
                                    if is_proc:
                                        log(f"  Still processing... ({int(elapsed)}s)")
                                except Exception:
                                    pass

                        await asyncio.sleep(0.5)

                    await asyncio.sleep(1)

                    # 9e2. Post-scan check: Validation Filter popup may appear
                    #      at the same instant as "Scan Completed" / Export enabled.
                    #      Check again AFTER the loop exits, before trying to export.
                    try:
                        if await validation_popup.first.is_visible():
                            log("Validation Filter popup detected (post-scan)!")
                            await save_screenshot(page2, f"validation_popup_{strategy}")
                            filter_not_qualified = True

                            # Close the popup
                            log("Closing popup...")
                            close_btn = page2.locator("xpath=/html/body/div[7]/div/table/tbody/tr[3]/td/div/table/tbody/tr/td/button")
                            closed = False
                            try:
                                await close_btn.wait_for(state="visible", timeout=3000)
                                await close_btn.click()
                                closed = True
                            except PlaywrightTimeout:
                                pass
                            if not closed:
                                try:
                                    await page2.get_by_role("button", name=re.compile(r"Close|OK", re.IGNORECASE)).first.click()
                                    closed = True
                                except Exception:
                                    pass
                            if not closed:
                                try:
                                    await page2.keyboard.press("Escape")
                                except Exception:
                                    pass
                            await asyncio.sleep(1)
                            log("Popup closed.")

                            # Uncheck Market trend filter
                            log("Unchecking Market trend filter...")
                            market_filter_cb = page2.locator(
                                "xpath=/html/body/div[4]/div[2]/div/div[2]/div[3]/div/div[3]"
                                "/div/div/div[2]/div/table[1]/tbody/tr[1]/td[5]/table/tbody/tr/td[1]"
                            )
                            try:
                                await market_filter_cb.wait_for(state="visible", timeout=3000)
                                await market_filter_cb.click()
                            except PlaywrightTimeout:
                                try:
                                    mf = page2.get_by_role("cell", name=re.compile(r"Market.*Filter|Market.*Trend", re.IGNORECASE)).locator("label, input, span").first
                                    await mf.click()
                                except Exception:
                                    log("Could not uncheck Market trend filter")
                            await asyncio.sleep(0.5)
                            log("Market trend filter unchecked")
                            notify(f"⚠️ <b>{strategy}</b>: Filter not qualified — re-scanning without market filter")

                            # Re-scan
                            log("Re-scanning without market filter...")
                            await page2.get_by_role("button", name="Scan").click()
                            log("Re-scan started...")

                            # Wait for re-scan to complete
                            rescan_start = time.time()
                            while time.time() - rescan_start < HARD_TIMEOUT_SECS:
                                try:
                                    if await export_btn.is_visible() and await export_btn.is_enabled():
                                        log(f"Re-scan completed! ({int(time.time()-rescan_start)}s)")
                                        scan_done = True
                                        break
                                except Exception:
                                    pass
                                try:
                                    zero_scrips = page2.get_by_text(re.compile(r"Qualified Scrips\s*:\s*0", re.IGNORECASE))
                                    if await zero_scrips.first.is_visible():
                                        log(f"Re-scan: 0 qualified scrips ({int(time.time()-rescan_start)}s)")
                                        no_qualified_scrips = True
                                        scan_done = True
                                        break
                                except Exception:
                                    pass
                                await asyncio.sleep(0.5)
                            await asyncio.sleep(1)
                    except Exception as vf_err:
                        log(f"Post-scan validation check error (non-fatal): {vf_err}")

                    # 9f. Export / save file
                    if scan_done and no_qualified_scrips:
                        filename  = f"{strategy}_{DATE_STR}_{RUN_LABEL}_No_Qualified_Scrips.csv"
                        save_path = DOWNLOAD_DIR / filename
                        save_path.write_text("")
                        log(f"Created empty file: {filename}")
                        notify(f"📄 <b>{strategy}</b>: 0 qualified scrips → {filename}")
                        tg_file(save_path, f"📄 <b>{strategy}</b> — 0 qualified scrips")
                        results.append(f"📄 {strategy} → {filename} (0 scrips)")

                    elif scan_done:
                        suffix = "_filter_not_qualified" if filter_not_qualified else ""
                        filename  = f"{strategy}_{DATE_STR}_{RUN_LABEL}{suffix}.csv"
                        save_path = DOWNLOAD_DIR / filename
                        log(f"Clicking Export → saving as: {filename}")
                        try:
                            async with page2.expect_download(timeout=60000) as dl_info:
                                await page2.get_by_role("button", name="Export").click()
                            download = await dl_info.value
                            await download.save_as(save_path)
                            log(f"File saved: {save_path}")
                            notify(f"✅ <b>{strategy}</b>: Saved as {filename}")
                            tg_file(save_path, f"✅ <b>{strategy}</b>")
                            results.append(f"✅ {strategy} → {filename}")
                        except PlaywrightTimeout:
                            await save_screenshot(page2, f"export_fail_{strategy}")
                            log(f"Download not captured for {strategy}.")
                            notify(f"⚠️ <b>{strategy}</b>: Download failed")
                            results.append(f"⚠️ {strategy} → download failed")

                    else:
                        await save_screenshot(page2, f"no_complete_{strategy}")
                        log(f"Skipping export for {strategy} — scan did not complete.")
                        notify(f"❌ <b>{strategy}</b>: Scan did not complete, skipped export")
                        results.append(f"❌ {strategy} → scan timed out")

                    break  # success — exit retry loop

                except Exception as e:
                    await save_screenshot(page2, f"error_{strategy}_attempt{attempt}")
                    log(f"Error on attempt {attempt}/{MAX_ATTEMPTS} for {strategy}: {e}")
                    if attempt < MAX_ATTEMPTS:
                        log("Waiting 5s before retry...")
                        notify(f"⚠️ <b>{strategy}</b>: Error on attempt {attempt}, retrying...")
                        await asyncio.sleep(5)
                    else:
                        log(f"All {MAX_ATTEMPTS} attempts failed for {strategy}.")
                        notify(f"❌ <b>{strategy}</b>: Failed after {MAX_ATTEMPTS} attempts — {e}")
                        results.append(f"❌ {strategy} → error: {e}")

            log(f"Strategy '{strategy}' done.\n")
            await asyncio.sleep(2)


        # ── ALL DONE ─────────────────────────────────────────────────────────
        separator("ALL STRATEGIES COMPLETE")
        log(f"Processed : {len(STRATEGIES)} strategies")
        log(f"Saved to  : {DOWNLOAD_DIR}")

        summary = "\n".join(results)
        log(f"\nResults:\n{summary}")
        tg(f"🏁 <b>RZ Scanner Complete (CI — {RUN_LABEL})</b>\n\n"
           + "\n".join(results)
           + f"\n\nDate: {DATE_STR}")

        await browser.close()
        log("Browser closed. Done.")


# ─────────────────────────────────────────────────────────────────────────────
async def main():
    """Wrapper that catches fatal errors and saves debug screenshots."""
    try:
        await run()
    except Exception as fatal:
        log(f"FATAL ERROR: {fatal}")
        notify(f"❌ <b>RZ Scanner CRASHED</b>\n{fatal}")
        raise


if __name__ == "__main__":
    asyncio.run(main())
